# Generated by Django 4.1.4 on 2022-12-11 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('numer_of_pages', models.PositiveIntegerField(verbose_name='Кол-во страниц')),
                ('author', models.CharField(max_length=255, verbose_name='Автор')),
            ],
        ),
    ]
