# Generated by Django 4.1.4 on 2022-12-13 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
                ('surname', models.CharField(max_length=255, verbose_name='Фамилия')),
                ('patronymic', models.CharField(max_length=255, verbose_name='Отчество')),
                ('year_of_birth', models.DateField(verbose_name='Год рождения')),
                ('country', models.CharField(max_length=255, verbose_name='Страна')),
                ('gander', models.CharField(choices=[('w', 'woman'), ('m', 'man')], max_length=255, verbose_name='Пол')),
            ],
        ),
    ]
